INCLUDEPATH += $$PWD

SOURCES += \
    $$PWD/gtstadministrator.cpp \
    $$PWD/gtstadministratordialog.cpp \
    $$PWD/gtstadministratordialogstate.cpp \
    $$PWD/gtstadministratordialogstateloggedin.cpp \
    $$PWD/gtstadministratordialogstatenotloggedin.cpp \
    $$PWD/gtstadministrators.cpp \
    $$PWD/gtstchatmessage.cpp \
    $$PWD/gtstchatshapefactory.cpp \
    $$PWD/gtstchooseactionoption.cpp \
    $$PWD/gtstdebugdialog.cpp \
    $$PWD/gtstgroup.cpp \
    $$PWD/gtstgroupassigner.cpp \
    $$PWD/gtstgroupfinished.cpp \
    $$PWD/gtstgrouploggedin.cpp \
    $$PWD/gtstgroupnotloggedin.cpp \
    $$PWD/gtstgroupparticipating.cpp \
    $$PWD/gtstgroups.cpp \
    $$PWD/gtstlogfile.cpp \
    $$PWD/gtstparameters.cpp \
    $$PWD/gtstparametersassignpayoff.cpp \
    $$PWD/gtstparameterschat.cpp \
    $$PWD/gtstparameterschooseaction.cpp \
    $$PWD/gtstparametersfinished.cpp \
    $$PWD/gtstparametersgroupassign.cpp \
    $$PWD/gtstparametersgroupreassign.cpp \
    $$PWD/gtstparametersquiz.cpp \
    $$PWD/gtstparametersviewresultsgroup.cpp \
    $$PWD/gtstparametersviewresultsvoting.cpp \
    $$PWD/gtstparametersvoting.cpp \
    $$PWD/gtstparticipant.cpp \
    $$PWD/gtstparticipantdialog.cpp \
    $$PWD/gtstparticipantdialogstate.cpp \
    $$PWD/gtstparticipantdialogstateassignpayoff.cpp \
    $$PWD/gtstparticipantdialogstatechat.cpp \
    $$PWD/gtstparticipantdialogstatechooseaction.cpp \
    $$PWD/gtstparticipantdialogstatefinished.cpp \
    $$PWD/gtstparticipantdialogstategroupassign.cpp \
    $$PWD/gtstparticipantdialogstategroupreassign.cpp \
    $$PWD/gtstparticipantdialogstateloggedin.cpp \
    $$PWD/gtstparticipantdialogstatenotloggedin.cpp \
    $$PWD/gtstparticipantdialogstatequiz.cpp \
    $$PWD/gtstparticipantdialogstates.cpp \
    $$PWD/gtstparticipantdialogstateviewresultsgroup.cpp \
    $$PWD/gtstparticipantdialogstateviewresultsvoting.cpp \
    $$PWD/gtstparticipantdialogstatevoting.cpp \
    $$PWD/gtstparticipantstate.cpp \
    $$PWD/gtstparticipantstateassignpayoff.cpp \
    $$PWD/gtstparticipantstatechat.cpp \
    $$PWD/gtstparticipantstatechooseaction.cpp \
    $$PWD/gtstparticipantstatefinished.cpp \
    $$PWD/gtstparticipantstategroupassign.cpp \
    $$PWD/gtstparticipantstategroupreassign.cpp \
    $$PWD/gtstparticipantstateloggedin.cpp \
    $$PWD/gtstparticipantstatenotloggedin.cpp \
    $$PWD/gtstparticipantstatequiz.cpp \
    $$PWD/gtstparticipantstateviewresultsgroup.cpp \
    $$PWD/gtstparticipantstateviewresultsvoting.cpp \
    $$PWD/gtstparticipantstatevoting.cpp \
    $$PWD/gtstpayoff.cpp \
    $$PWD/gtstpayoffs.cpp \
    $$PWD/gtstmenudialog.cpp \
    $$PWD/gtstrepeatassigner.cpp \
    $$PWD/gtstrepeatassignerfixed.cpp \
    $$PWD/gtstrepeatassignerrandomgeometric.cpp \
    $$PWD/gtstrepeatassignerrandomuniform.cpp \
    $$PWD/gtstresources.cpp \
    $$PWD/gtstserver.cpp \
    $$PWD/gtstserverstate.cpp \
    $$PWD/gtstserverstateassignpayoff.cpp \
    $$PWD/gtstserverstatechat.cpp \
    $$PWD/gtstserverstatechooseaction.cpp \
    $$PWD/gtstserverstatefinished.cpp \
    $$PWD/gtstserverstategroupassign.cpp \
    $$PWD/gtstserverstategroupreassign.cpp \
    $$PWD/gtstserverstatequiz.cpp \
    $$PWD/gtstserverstates.cpp \
    $$PWD/gtstserverstateviewresultsgroup.cpp \
    $$PWD/gtstserverstateviewresultsvoting.cpp \
    $$PWD/gtstserverstatevoting.cpp \
    $$PWD/gtstserverstatewaiting.cpp \
    $$PWD/gtststate.cpp \
    $$PWD/gtsttest.cpp \
    $$PWD/gtsttestparameterparsing.cpp \
    $$PWD/gtsttestparameters.cpp \
    $$PWD/gtsttestparticipant.cpp \
    $$PWD/gtstteststate.cpp \
    $$PWD/gtstvote.cpp \
    $$PWD/gtstvotingoption.cpp

HEADERS += \
    $$PWD/gtstadministrator.h \
    $$PWD/gtstadministratordialog.h \
    $$PWD/gtstadministratordialogstate.h \
    $$PWD/gtstadministratordialogstateloggedin.h \
    $$PWD/gtstadministratordialogstatenotloggedin.h \
    $$PWD/gtstadministrators.h \
    $$PWD/gtstall_groups.h \
    $$PWD/gtstall_parameters.h \
    $$PWD/gtstall_participantdialogstates.h \
    $$PWD/gtstall_participantstates.h \
    $$PWD/gtstall_serverstates.h \
    $$PWD/gtstchatmessage.h \
    $$PWD/gtstchatshapefactory.h \
    $$PWD/gtstchooseactionoption.h \
    $$PWD/gtstdebugdialog.h \
    $$PWD/gtstforward_declarations.h \
    $$PWD/gtstgroup.h \
    $$PWD/gtstgroupassigner.h \
    $$PWD/gtstgroupfinished.h \
    $$PWD/gtstgrouploggedin.h \
    $$PWD/gtstgroupnotloggedin.h \
    $$PWD/gtstgroupparticipating.h \
    $$PWD/gtstgroups.h \
    $$PWD/gtstlogfile.h \
    $$PWD/gtstparameters.h \
    $$PWD/gtstparametersassignpayoff.h \
    $$PWD/gtstparameterschat.h \
    $$PWD/gtstparameterschooseaction.h \
    $$PWD/gtstparametersfinished.h \
    $$PWD/gtstparametersgroupassign.h \
    $$PWD/gtstparametersgroupreassign.h \
    $$PWD/gtstparametersquiz.h \
    $$PWD/gtstparametersviewresultsall.h \
    $$PWD/gtstparametersviewresultsgroup.h \
    $$PWD/gtstparametersviewresultsvoting.h \
    $$PWD/gtstparametersvoting.h \
    $$PWD/gtstparticipant.h \
    $$PWD/gtstparticipantdialog.h \
    $$PWD/gtstparticipantdialogstate.h \
    $$PWD/gtstparticipantdialogstateassignpayoff.h \
    $$PWD/gtstparticipantdialogstatechat.h \
    $$PWD/gtstparticipantdialogstatechooseaction.h \
    $$PWD/gtstparticipantdialogstatefinished.h \
    $$PWD/gtstparticipantdialogstategroupassign.h \
    $$PWD/gtstparticipantdialogstategroupreassign.h \
    $$PWD/gtstparticipantdialogstateloggedin.h \
    $$PWD/gtstparticipantdialogstatenotloggedin.h \
    $$PWD/gtstparticipantdialogstatequiz.h \
    $$PWD/gtstparticipantdialogstates.h \
    $$PWD/gtstparticipantdialogstateviewresultsgroup.h \
    $$PWD/gtstparticipantdialogstateviewresultsvoting.h \
    $$PWD/gtstparticipantdialogstatevoting.h \
    $$PWD/gtstparticipantstate.h \
    $$PWD/gtstparticipantstateassignpayoff.h \
    $$PWD/gtstparticipantstatechat.h \
    $$PWD/gtstparticipantstatechooseaction.h \
    $$PWD/gtstparticipantstatefinished.h \
    $$PWD/gtstparticipantstategroupassign.h \
    $$PWD/gtstparticipantstategroupreassign.h \
    $$PWD/gtstparticipantstateloggedin.h \
    $$PWD/gtstparticipantstatenotloggedin.h \
    $$PWD/gtstparticipantstatequiz.h \
    $$PWD/gtstparticipantstateviewresultsgroup.h \
    $$PWD/gtstparticipantstateviewresultsvoting.h \
    $$PWD/gtstparticipantstatevoting.h \
    $$PWD/gtstpayoff.h \
    $$PWD/gtstpayoffs.h \
    $$PWD/gtstmenudialog.h \
    $$PWD/gtstrepeatassigner.h \
    $$PWD/gtstrepeatassignerfixed.h \
    $$PWD/gtstrepeatassignerrandomgeometric.h \
    $$PWD/gtstrepeatassignerrandomuniform.h \
    $$PWD/gtstresources.h \
    $$PWD/gtstserver.h \
    $$PWD/gtstserverstate.h \
    $$PWD/gtstserverstateassignpayoff.h \
    $$PWD/gtstserverstatechat.h \
    $$PWD/gtstserverstatechooseaction.h \
    $$PWD/gtstserverstatefinished.h \
    $$PWD/gtstserverstategroupassign.h \
    $$PWD/gtstserverstategroupreassign.h \
    $$PWD/gtstserverstatequiz.h \
    $$PWD/gtstserverstates.h \
    $$PWD/gtstserverstateviewresultsgroup.h \
    $$PWD/gtstserverstateviewresultsvoting.h \
    $$PWD/gtstserverstatevoting.h \
    $$PWD/gtstserverstatewaiting.h \
    $$PWD/gtststate.h \
    $$PWD/gtsttest.h \
    $$PWD/gtstvote.h \
    $$PWD/gtstvotingoption.h

RESOURCES += \
    $$PWD/ProjectGtst.qrc
